# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Campaign.destroy_all
Review.destroy_all
Character.destroy_all

puts 'Clearing the database, one moment....'

puts 'Planting seeds...'

puts 'Creating users...'
User.create (user_id: 1, first_name: "Devin", last_name: "Heinzler", email_address: "devinheinzler271@gmail.com", password: "example1")
User.create (user_id: 2, first_name: "Kate", last_name: "Gelati", email_address: "kateg@gmail.com", password: "example2")
User.create (user_id: 3, first_name: "Kevin", last_name: "Sasse", email_address: "kevins@gmail.com", password: "example3")
User.create (user_id: 4, first_name: "Misha", last_name: "Tuesday", email_address: "mishatue@gmail.com", password: "example4")
User.create (user_id: 5, first_name: "Bo", last_name: "Hauptly", email_address: "bohaup@gmail.com", password: "example5")

puts "Creating some cool campaigns, this may take a minute..."
Campaign.create (campaign_id: 1, 
campaign_title: "The Dark Tower", 
campaign_story: "The kingdom of Andalasia is being threatened by a dark force that is slowly taking over the land. A powerful necromancer, who has been using dark magic to raise the dead, is planning to take over the kingdom and plunge it into eternal darkness. The players are a group of heroes who must journey to the Dark Tower, where the necromancer resides, and stop him before it's too late.", 
campaign_setting: "The kingdom of Andalasia, a medieval fantasy realm with small villages, dense forests, and treacherous mountains. The kingdom is ruled by a wise and benevolent king, but recently, strange things have been happening in the land. Strange creatures have been sighted, and some of the villagers have gone missing.", 
campaign_NPCs: "King Reginald: The wise and benevolent ruler of Andalasia. He enlists the players to help save the kingdom. Sir William: A skilled knight and old friend of the players. He joins them on their quest to the Dark Tower. Elora: A mysterious ranger who knows the land well and is able to provide valuable information and guidance to the players. Aria: A powerful sorceress who is able to use her magic to aid the players in their quest. The Necromancer: The main antagonist of the campaign, he is a powerful sorcerer who is using dark magic to raise the dead and take over the kingdom.", 
campaign_challenges: "The players must navigate the treacherous forests and mountains to reach the Dark Tower. They will encounter various creatures along the way, such as goblins, trolls, and undead skeletons, that they must battle in order to continue on their quest. The players will also have to solve puzzles and riddles in order to proceed, as the Dark Tower is filled with traps and other dangers. Once they reach the Dark Tower, they must face off against the Necromancer and his army of undead minions in a final, epic battle.", 
campaign_climax: "The players reach the Dark Tower and face off against the Necromancer in a final battle. Using their skills and abilities, they are able to defeat the Necromancer and save the kingdom from his evil plans.", 
campaign_aftermath: "The kingdom is saved, and the players are hailed as heroes. They return to their villages, where they are greeted with celebrations and rewards. The kingdom is able to return to a state of peace and prosperity, thanks to the bravery and determination of the players.")
Campaign.create (campaign_id: 2, 
campaign_title: "The Crown of the Shadow King", 
campaign_story: "The players are a group of adventurers who have been hired by the resistance, a secret group of rebels fighting against the Shadow King's rule. The resistance has learned of a powerful artifact known as the Crown of the Shadow King, which is said to grant its wearer immense magical powers. The players must journey to the Shadow King's castle, located in the heart of the dark forest, and retrieve the crown before the Shadow King can use its power to cement his rule over the kingdom.", 
campaign_setting: "The kingdom of Ravenwood, a dark and foreboding land ruled by the tyrannical Shadow King. The kingdom is bordered by treacherous mountains to the north, a deep and murky swamp to the south, and a sprawling forest to the east. The only safe haven for travelers is the bustling city of Evermore, located in the heart of the kingdom.", 
campaign_NPCs: "The Shadow King: The tyrannical ruler of Ravenwood, the Shadow King is a powerful sorcerer who will stop at nothing to maintain his grip on the kingdom. The resistance leader: The leader of the resistance, a wise and experienced warrior who enlists the players to retrieve the Crown of the Shadow King. The Castlekeeper: The mysterious caretaker of the Shadow King's castle, the Castlekeeper is a formidable opponent who guards the entrance to the castle. The ancient wizard: A wise and ancient wizard who has been imprisoned in the dungeons of the Shadow King's castle for many years. He holds the key to unlocking the power of the Crown of the Shadow King, and the players must free him if they hope to succeed in their mission.", 
campaign_challenges: "The treacherous journey to the Shadow King's castle: The players must navigate the dangerous forest and avoid the Shadow King's patrols if they hope to reach the castle. The Castlekeeper: The Castlekeeper will not let the players enter the castle easily, and they must defeat him in combat or outsmart him in order to gain access. The Shadow King's guards: The castle is filled with the Shadow King's loyal guards, who will stop at nothing to protect their master. The players must fight their way through the castle and defeat the guards if they hope to reach the Crown of the Shadow King.", 
campaign_climax: "The players finally reach the Crown of the Shadow King, but they discover that it is guarded by a powerful magical beast. In a tense and epic battle, the players must use all of their skills and knowledge to defeat the beast and claim the crown.", 
campaign_aftermath: "With the Crown of the Shadow King in their possession, the players must make a difficult decision. Do they use the crown's power to overthrow the Shadow King and take control of the kingdom themselves, or do they destroy the crown and prevent its power from falling into the wrong hands? The outcome of their decision will shape the future of Ravenwood and determine the fate of its people.")
Campaign.create (campaign_id: 3, 
campaign_title: "The Cursed Tomb of the Unquiet Dead", 
campaign_story: "The players must journey through the treacherous valley, braving dangerous creatures and treacherous terrain in order to reach the tomb. Along the way, they will encounter several non-player characters (NPCs) who will either help or hinder their progress, including a wise old hermit who knows the secrets of the valley, a band of ruthless mercenaries who are also after the artifact, and a tribe of barbarians who worship the ancient evil that is said to haunt the valley.", 
campaign_setting: "The campaign takes place in a remote and desolate valley, rumored to be cursed by an ancient evil. The players are a group of adventurers who have been hired by a wealthy collector to explore the valley and retrieve a powerful artifact that is said to be hidden in a long-abandoned tomb at its center.", 
campaign_challenges: "The players will face a variety of challenges on their journey, including treacherous weather, hostile creatures, and difficult puzzles and traps. They will also have to navigate the complex politics of the various factions in the valley, choosing which allies to trust and which enemies to face.", 
campaign_climax: "As the players reach the tomb and attempt to retrieve the artifact, they will discover that it is guarded by a powerful undead sorcerer who was once the ruler of the valley. The sorcerer has been cursed to remain in the tomb for eternity, and will stop at nothing to prevent the players from taking the artifact. The players will have to use all of their skills and cunning to defeat the sorcerer and claim the artifact.", 
campaign_aftermath: "After the players successfully retrieve the artifact and defeat the undead sorcerer, they must make their way back out of the valley. Along the way, they will have to deal with the consequences of their actions, including the wrath of the mercenaries and the barbarians who were defeated by the players. The players will also have to decide what to do with the artifact, as its power could be dangerous in the wrong hands.",
campaign_NPCs: "Here's your chance to think a little outside the box! Using examples from other campaigns, feel free to create the NPCs you'll encounter in your world!")

puts 'Creating reviews for all the campaigns, stand by...'
Review.create(review_id: 1, user_id: 1, campaign_id: 1, campaign_title: "The Dark Tower", review_content: "Hoenstly a mid-tier campaign, but was fun for my friends that were new to the game", star_rating: 3)
Review.create(review_id: 2, user_id: 2, campaign_id: 2, campaign_title: "The Crown of the Shadow King", review_content: "Great time, quick and easy. A little shallow.", star_rating: 4)
Review.create(review_id: 3, user_id: 3, campaign_id: 3, campaign_title: "The Cursed Tomb of the Unquiet Dead", review_content: "Didn't like that we had to create more of our own stuff", star_rating: 2)
Review.create(review_id: 4, user_id: 4, campaign_id: 1, campaign_title: "The Dark Tower", review_content: "Amazing campaign, we're all new to this and it was a great way to get our boots on the ground", star_rating: 5)
Review.create(review_id: 5, user_id: 5, campaign_id: 2, campaign_title: "The Crown of the Shadow King", review_content: "Great room for adding your own stuff. Big fan", star_rating: 4)
Review.create(review_id: 6, user_id: 3, campaign_id: 3, campaign_title: "The Cursed Tomb of the Unquiet Dead", review_content: "Loved the extra room for our own creativity!", star_rating: )

puts "Creatin some characters, not an easy task..."
Character.create(user_id: 1, campaign_id: 1, character_name: "Vogoth", character_image: "", race_name: "Dragonborn", race_image: "", race_description: "Dragonborn tend to extremes, making a conscious choice for one side or the other in the cosmic war between good and evil. Most dragonborn are good, but those who side with evil can be terrible villains.", race_trait_name: "breath-weapon", class_name: "Cleric", class_image: "", subclass: "Life", subclass_feature: "Blessed Healer", race_proficiencies: "No race proficiencies available", character_background: "Acolyte", character_language: "Draconic", character_alignment: "Chaotic-Good", character_notes: "very cool")
Character.create(user_id: 2, campaign_id: 2, character_name: "Admar", character_image: "", race_name: "Dwarf", race_image: "", race_description: "Most dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of fair play and a belief that everyone deserves to share in the benefits of a just order.", race_trait_name: "tool-proficiency", class_name: "Druid", class_image: "", subclass: "Land", subclass_feature: "Natural Recovery", race_proficiencies: "Battleaxes", character_background: "Acolyte", character_language: "Dwarvish", character_alignment: "Chaotic-Evil", character_notes: "likes dwarfs")
Character.create(user_id: 3, campaign_id: 3, character_name: "Heinzy", character_image: "", race_name: "Elf", race_image: "", race_description: "Elves love freedom, variety, and self-expression, so they lean strongly toward the gentler aspects of chaos. They value and protect others' freedom as well as their own, and they are more often good than not. The drow are an exception; their exile has made them vicious and dangerous. Drow are more often evil than not.", race_trait_name: "key-senses", class_name: "Bard", class_image: "", subclass: "Lore", subclass_feature: "Cutting Words", race_proficiencies: "Skill: Perception", character_background: "Acolyte", character_language: "Elvish", character_alignment: "Lawful-Neutral", character_notes: "hates dwarfs")
Character.create(user_id: 4, campaign_id: 2, character_name: "Ba'al", character_image: "", race_name: "Gnome", race_image: "", race_description: "Gnomes are most often good. Those who tend toward law are sages, engineers, researchers, scholars, investigators, or inventors. Those who tend toward chaos are minstrels, tricksters, wanderers, or fanciful jewelers. Gnomes are good-hearted, and even the tricksters among them are more playful than vicious.", race_trait_name: "darkvision", class_name: "Barbarian", class_image: "", subclass: "Berserker", subclass_feature: "Frenzy", race_proficiencies: "No race proficiencies available", character_background: "Acolyte", character_language: "Gnomish", character_alignment: "Neutral", character_notes: "Strategist")
Character.create(user_id: 5, campaign_id: 3, character_name: "Pip", character_image: "", race_name: "Half-Elf", race_image: "", race_description: "Half-elves share the chaotic bent of their elven heritage. They value both personal freedom and creative expression, demonstrating neither love of leaders nor desire for followers. They chafe at rules, resent others' demands, and sometimes prove unreliable, or at least unpredictable.", race_trait_name: "skill-versatility", class_name: "Fighter", class_image: "", subclass: "Champion", subclass_feature: "Imporved Critical", race_proficiencies: "No race proficiencies available", character_background: "Acolyte", character_language: "Common", character_alignment: "Neutral-Good", character_notes: "Makes bad decisions")
Character.create(user_id: 2, campaign_id: 1, character_name: "Annalise", character_image: "", race_name: "Human", race_image: "", race_description: "Humans tend toward no particular alignment. The best and the worst are found among them.", race_trait_name: "Human's currently have no specified race traits", class_name: "Monk", class_image: "", subclass: "Open-Hand", subclass_feature: "Tranquility", race_proficiencies: "No race proficiencies available", character_background: "Acolyte", character_language: "Common", character_alignment: "", character_notes: "Is very very lucky")
Character.create(user_id: 4, campaign_id: 3, character_name: "Ivin", character_image: "", race_name: "Halfling", race_image: "", race_description: "Most halflings are lawful good. As a rule, they are good-hearted and kind, hate to see others in pain, and have no tolerance for oppression. They are also very orderly and traditional, leaning heavily on the support of their community and the comfort of their old ways.", race_trait_name: "lucky", class_name: "Paladin", class_image: "", subclass: "Devotion", subclass_feature: "Purity of Spirit", race_proficiencies: "No race proficiencies available", character_background: "Acolyte", character_language: "Under-Common", character_alignment: "Lawful-Evil", character_notes: "Doesn't have a clue what's going on")

puts 'Seeding done, whew!'