# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Campaign.destroy_all
Review.destroy_all
Character.destroy_all

puts 'Clearing the database, one moment....'

puts 'Planting seeds...'

puts 'Creating users...'
User.create(first_name: "Devin", last_name: "Heinzler", email_address: "devinheinzler271@gmail.com", password: "example1")
User.create(first_name: "Kate", last_name: "Gelati", email_address: "kateg@gmail.com", password: "example2")
User.create(first_name: "Kevin", last_name: "Sasse", email_address: "kevins@gmail.com", password: "example3")
User.create(first_name: "Misha", last_name: "Tuesday", email_address: "mishatue@gmail.com", password: "example4")
User.create(first_name: "Bo", last_name: "Hauptly", email_address: "bohaup@gmail.com", password: "example5")

puts "Creating some cool campaigns, this may take a minute..."
Campaign.create( 
campaign_title: "The Dark Tower", 
campaign_story: "The kingdom of Andalasia is being threatened by a dark force that is slowly taking over the land. A powerful necromancer, who has been using dark magic to raise the dead, is planning to take over the kingdom and plunge it into eternal darkness. The players are a group of heroes who must journey to the Dark Tower, where the necromancer resides, and stop him before it's too late.", 
campaign_setting: "The kingdom of Andalasia, a medieval fantasy realm with small villages, dense forests, and treacherous mountains. The kingdom is ruled by a wise and benevolent king, but recently, strange things have been happening in the land. Strange creatures have been sighted, and some of the villagers have gone missing.", 
campaign_NPCs: "King Reginald: The wise and benevolent ruler of Andalasia. He enlists the players to help save the kingdom. Sir William: A skilled knight and old friend of the players. He joins them on their quest to the Dark Tower. Elora: A mysterious ranger who knows the land well and is able to provide valuable information and guidance to the players. Aria: A powerful sorceress who is able to use her magic to aid the players in their quest. The Necromancer: The main antagonist of the campaign, he is a powerful sorcerer who is using dark magic to raise the dead and take over the kingdom.", 
campaign_challenges: "The players must navigate the treacherous forests and mountains to reach the Dark Tower. They will encounter various creatures along the way, such as goblins, trolls, and undead skeletons, that they must battle in order to continue on their quest. The players will also have to solve puzzles and riddles in order to proceed, as the Dark Tower is filled with traps and other dangers. Once they reach the Dark Tower, they must face off against the Necromancer and his army of undead minions in a final, epic battle.", 
campaign_climax: "The players reach the Dark Tower and face off against the Necromancer in a final battle. Using their skills and abilities, they are able to defeat the Necromancer and save the kingdom from his evil plans.", 
campaign_aftermath: "The kingdom is saved, and the players are hailed as heroes. They return to their villages, where they are greeted with celebrations and rewards. The kingdom is able to return to a state of peace and prosperity, thanks to the bravery and determination of the players.")
Campaign.create( 
campaign_title: "The Crown of the Shadow King", 
campaign_story: "The players are a group of adventurers who have been hired by the resistance, a secret group of rebels fighting against the Shadow King's rule. The resistance has learned of a powerful artifact known as the Crown of the Shadow King, which is said to grant its wearer immense magical powers. The players must journey to the Shadow King's castle, located in the heart of the dark forest, and retrieve the crown before the Shadow King can use its power to cement his rule over the kingdom.", 
campaign_setting: "The kingdom of Ravenwood, a dark and foreboding land ruled by the tyrannical Shadow King. The kingdom is bordered by treacherous mountains to the north, a deep and murky swamp to the south, and a sprawling forest to the east. The only safe haven for travelers is the bustling city of Evermore, located in the heart of the kingdom.", 
campaign_NPCs: "The Shadow King: The tyrannical ruler of Ravenwood, the Shadow King is a powerful sorcerer who will stop at nothing to maintain his grip on the kingdom. The resistance leader: The leader of the resistance, a wise and experienced warrior who enlists the players to retrieve the Crown of the Shadow King. The Castlekeeper: The mysterious caretaker of the Shadow King's castle, the Castlekeeper is a formidable opponent who guards the entrance to the castle. The ancient wizard: A wise and ancient wizard who has been imprisoned in the dungeons of the Shadow King's castle for many years. He holds the key to unlocking the power of the Crown of the Shadow King, and the players must free him if they hope to succeed in their mission.", 
campaign_challenges: "The treacherous journey to the Shadow King's castle: The players must navigate the dangerous forest and avoid the Shadow King's patrols if they hope to reach the castle. The Castlekeeper: The Castlekeeper will not let the players enter the castle easily, and they must defeat him in combat or outsmart him in order to gain access. The Shadow King's guards: The castle is filled with the Shadow King's loyal guards, who will stop at nothing to protect their master. The players must fight their way through the castle and defeat the guards if they hope to reach the Crown of the Shadow King.", 
campaign_climax: "The players finally reach the Crown of the Shadow King, but they discover that it is guarded by a powerful magical beast. In a tense and epic battle, the players must use all of their skills and knowledge to defeat the beast and claim the crown.", 
campaign_aftermath: "With the Crown of the Shadow King in their possession, the players must make a difficult decision. Do they use the crown's power to overthrow the Shadow King and take control of the kingdom themselves, or do they destroy the crown and prevent its power from falling into the wrong hands? The outcome of their decision will shape the future of Ravenwood and determine the fate of its people.")
Campaign.create( 
campaign_title: "The Cursed Tomb of the Unquiet Dead", 
campaign_story: "The players must journey through the treacherous valley, braving dangerous creatures and treacherous terrain in order to reach the tomb. Along the way, they will encounter several non-player characters (NPCs) who will either help or hinder their progress, including a wise old hermit who knows the secrets of the valley, a band of ruthless mercenaries who are also after the artifact, and a tribe of barbarians who worship the ancient evil that is said to haunt the valley.", 
campaign_setting: "The campaign takes place in a remote and desolate valley, rumored to be cursed by an ancient evil. The players are a group of adventurers who have been hired by a wealthy collector to explore the valley and retrieve a powerful artifact that is said to be hidden in a long-abandoned tomb at its center.", 
campaign_challenges: "The players will face a variety of challenges on their journey, including treacherous weather, hostile creatures, and difficult puzzles and traps. They will also have to navigate the complex politics of the various factions in the valley, choosing which allies to trust and which enemies to face.", 
campaign_climax: "As the players reach the tomb and attempt to retrieve the artifact, they will discover that it is guarded by a powerful undead sorcerer who was once the ruler of the valley. The sorcerer has been cursed to remain in the tomb for eternity, and will stop at nothing to prevent the players from taking the artifact. The players will have to use all of their skills and cunning to defeat the sorcerer and claim the artifact.", 
campaign_aftermath: "After the players successfully retrieve the artifact and defeat the undead sorcerer, they must make their way back out of the valley. Along the way, they will have to deal with the consequences of their actions, including the wrath of the mercenaries and the barbarians who were defeated by the players. The players will also have to decide what to do with the artifact, as its power could be dangerous in the wrong hands.",
campaign_NPCs: "Here's your chance to think a little outside the box! Using examples from other campaigns, feel free to create the NPCs you'll encounter in your world!")

puts 'Creating reviews for all the campaigns, stand by...'
Review.create(user_id: 1, campaign_id: 1, campaign_title: "The Dark Tower", review_content: "Hoenstly a mid-tier campaign, but was fun for my friends that were new to the game", star_rating: 3)
Review.create(user_id: 2, campaign_id: 2, campaign_title: "The Crown of the Shadow King", review_content: "Great time, quick and easy. A little shallow.", star_rating: 4)
Review.create(user_id: 3, campaign_id: 3, campaign_title: "The Cursed Tomb of the Unquiet Dead", review_content: "Didn't like that we had to create more of our own stuff", star_rating: 2)
Review.create(user_id: 4, campaign_id: 1, campaign_title: "The Dark Tower", review_content: "Amazing campaign, we're all new to this and it was a great way to get our boots on the ground", star_rating: 5)
Review.create(user_id: 5, campaign_id: 2, campaign_title: "The Crown of the Shadow King", review_content: "Great room for adding your own stuff. Big fan", star_rating: 4)
Review.create(user_id: 3, campaign_id: 3, campaign_title: "The Cursed Tomb of the Unquiet Dead", review_content: "Loved the extra room for our own creativity!", star_rating: 4)

puts 'Creating character templates....'
template1 = CharacterTemplate.create(character_name: "Fighter 1", character_image: "", race_name: "Halfling", race_trait_name: "Halfling Nimbleness and Lucky", class_name: "Monk", class_image: "", subclass_feature: "Martial Arts", race_proficiencies: "Str +1, Dex +6, and an advantage against being frightened or poisoned", character_background: "You spent your formative years in a monastery dedicated to the Triad—Torm, Tyr, and primarily for your order, Ilmater, god of endurance and martyrdom. As a priest, you can perform sacred rites, including counseling and aiding others. A member of the order of the Gauntlet, approach situations with diplomacy, help those in need, and place too much trust in faith.", character_alignment: "Lawful-Good")
template2 = CharacterTemplate.create(character_name: "Fighter 2", character_image: "", race_name: "Human", race_trait_name: "Martial Weapons, Passive Perception 12", class_name: "Fighter", class_image: "", subclass_feature: "Protective Fighting Style: impose disadvantage on an attack roll when wielding a shield, Second Wind: Use a bonus action to regain 1d10 + 1 hit points (Must complete rest period before use.)", race_proficiencies: "Str +5, Con +4", character_background: "You were a professional soldier. You traveled to foreign lands, led troops into danger, fought wars under the banners of different commanders. Yet, you craved something more out of life, and resigned your commission. Now you are out on your own, living by your wits, taking orders from no one. You're recognized as a soldier wherever you go, a member of the order of the Gauntlet, never flinch, embrace tyranny, fight for the common folk, and never admit that you're wrong.", character_alignment: "Chaotic-Good")
template3 = CharacterTemplate.create(character_name: "Scoundrel 1", character_image: "", race_name: "Half-Elf", race_trait_name: "Fey Ancestry: Immune to magical sleep effects", class_name: "Bard", class_image: "", subclass_feature: "Spellcasting Ability: You have the ability to cast spells by using Charisma.", race_proficiencies: "Dex +5, Cha +5, advantage against being chared.", character_background: "You have been the center of attention since before you could walk, and once you learned to sing and play, you never surrendered the spotlight again. And who deserves it more than you? You always find food and lodging as long as you're performing, strangers take a liking to you, a member of the Harpers, change your mood very quickly, make the world better when you perform, always want to prove yourself better than a rival, and a sucker for a pretty face.", character_alignment: "Neutral-Good")
template4 = CharacterTemplate.create(character_name: "Scoundrel 2", character_image: "", race_name: "Halfling", race_trait_name: "Halfling Nimbleness and Lucky", class_name: "Rogue", class_image: "", subclass_feature: "Sneak Attack: Deal an extra 1d6 damage once per turn if you have advantage on the attack roll.", race_proficiencies: "Dex +5, Int +4, keen to acrobatics.", character_background: "You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts within the criminal underworld. You have survived up to this point by flouting the rules and regulations of society.Your expertise is burglary. You are unmatched at getting into tight spaces and locked rooms, and getting back out again richer and none the worse. ", character_alignment: "Neutral")
template5 = CharacterTemplate.create(character_name: "Mage 1", character_image: "", race_name: "Dragon-Born", race_trait_name: "Breath-Weapon: Use your action to exhale cold energy in a 15-foot cone. Each creature in the area must make a DC Constitution saving throw. Dragonic Ancestry(Silver): Cold breath weapon and resistance to cold.", class_name: "Sorcerer", class_image: "", subclass_feature: "Spellcasting: Ability to cast sorcerer spells using Charisma, Spell Save DC: 13, Spell attack modifier: +5", race_proficiencies: "Con +4, Cha +6", character_background: "You grew up in the wilds, a fiercely proud member of a noble clan. The clan outweighs everything else in your life, even the stated law of the land. Wanderer: You have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided that the land offers berries, small game, water, and so forth. A member of the Emerald Enclave, you'd do anything to protect the clan, you have ideallic values, your clan is the most important thing in your life, you believe in survival of the fittest.", character_alignment: "Neutral-Good")
template6 = CharacterTemplate.create(character_name: "Mage 2", character_image: "", race_name: "Human", race_trait_name: "Martial Weapons, Passive Perception 12", class_name: "Druid", class_image: "", subclass_feature: "Spellcasting: Drawing on the divine essence of nature, you can cast spells to shape that essence to your will. Druidic: Speak druidic to leave hidden messages and decipher hidden messages", race_proficiencies: "Light Armor, Medium Armor, Shields.", character_background: "You come from among the peasantry, but the druids who taught you revealed your birth is in accord with a prophecy spoken long ago by mysterious fey. People of your home village regard you as a blessed one with the skills to stand against threats against common folk everywhere. Rustic Hospitality: You can find a place to hide, rest, or recuperate among commoners, unless you have shown yourself to be a danger to them. They will shield you from the law or anyone else searching for you, though they will not risk their lives for you. A member of the Emerald Enclave, you judge people by their actions and test them with strong words, tradition is very important, everything you do is to serve and protect the common folk, and you're convinced that everything that happens to you is part of your destiny.", character_alignment: "Neutral-Good")
template7 = CharacterTemplate.create(character_name: "Healer 1", character_image: "", race_name: "Dwarf", race_trait_name: "Darkvision: You can see in the dark, Stonecutting: +4 bonus on Intelligence (History) checks related to stonecutting.", class_name: "Cleric", class_image: "", subclass_feature: "Life Dommain: Gain access to Disciple of Life: When you restore hitpoints to a creature, the creature gains additional hitpoints equal to +2 the spell's level. Spell Casting: Drawing on the divine essense of nature, you can cast spells to shape that essence to your will.", race_proficiencies: "Wis +5, Cha +3, advantage against being poisoned.", character_background: "Before you became devoted to the dwarven deities, you were a journeyman jeweler and gem cutter. Even outside your home, you are recognized by your badge and skill. You have the aid of a loose coalition of guilds, and one day you shall become a master your own right. Seeking such mastery is an act of worship to you. Guild Member: Fellow guild members can provide you with necessities, and the guild can use its political power to aid you. In some areas, a guildhall offers a place to meet other members of your profession and those who aid the guild. You must pay dues of 5 gp per month to the guild. If you miss payments, you must make up back dues to remain in the guild's good graces.", character_alignment: "Lawful-Good")
template8 = CharacterTemplate.create(character_name: "Healer 2", character_image: "", race_name: "Human", race_trait_name: "Martial Weapons, Passive Perception 12", class_name: "Paladin", class_image: "", subclass_feature: "Divine Sense: Activite to gain awareness for the duration of your turn, revealing the location of any celestial, fiend, or undead within 60 feet of you that is not behind cover.", race_proficiencies: "Wis +3, Cha +4", character_background: "You were born the eighth child of a minor noble family. You are accustomed to privilege and the comforts that come with it, but recognizing that you will never inherit, you set out as a youth to find your own path.  Position of Privilege: Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are. The common folk make every effort to accommodate you and avoid your displeasure, and other people of high birth treat you as a member of the same social sphere. You can secure an audience with a local noble if you need to.", character_alignment: "Lawful-Good")

puts "Creatin some characters, not an easy task..."
Character.create(character_template_id: template1.id, user_id: 1, campaign_id: 1, character_name: "Fighter 1", character_image: "", race_name: "Halfling", race_trait_name: "Halfling Nimbleness and Lucky", class_name: "Monk", class_image: "", subclass_feature: "Martial Arts", race_proficiencies: "Str +1, Dex +6, and an advantage against being frightened or poisoned", character_background: "You spent your formative years in a monastery dedicated to the Triad—Torm, Tyr, and primarily for your order, Ilmater, god of endurance and martyrdom. As a priest, you can perform sacred rites, including counseling and aiding others. A member of the order of the Gauntlet, approach situations with diplomacy, help those in need, and place too much trust in faith.", character_alignment: "Lawful-Good", character_notes: "very cool")
Character.create(character_template_id: template2.id, user_id: 2, campaign_id: 2, character_name: "Fighter 2", character_image: "", race_name: "Human", race_trait_name: "Martial Weapons, Passive Perception 12", class_name: "Fighter", class_image: "", subclass_feature: "Protective Fighting Style: impose disadvantage on an attack roll when wielding a shield, Second Wind: Use a bonus action to regain 1d10 + 1 hit points (Must complete rest period before use.)", race_proficiencies: "Str +5, Con +4", character_background: "You were a professional soldier. You traveled to foreign lands, led troops into danger, fought wars under the banners of different commanders. Yet, you craved something more out of life, and resigned your commission. Now you are out on your own, living by your wits, taking orders from no one. You're recognized as a soldier wherever you go, a member of the order of the Gauntlet, never flinch, embrace tyranny, fight for the common folk, and never admit that you're wrong.", character_alignment: "Chaotic-Good", character_notes: "likes dwarfs")
Character.create(character_template_id: template3.id, user_id: 3, campaign_id: 3, character_name: "Scoundrel 1", character_image: "", race_name: "Half-Elf", race_trait_name: "Fey Ancestry: Immune to magical sleep effects", class_name: "Bard", class_image: "", subclass_feature: "Spellcasting Ability: You have the ability to cast spells by using Charisma.", race_proficiencies: "Dex +5, Cha +5, advantage against being chared.", character_background: "You have been the center of attention since before you could walk, and once you learned to sing and play, you never surrendered the spotlight again. And who deserves it more than you? You always find food and lodging as long as you're performing, strangers take a liking to you, a member of the Harpers, change your mood very quickly, make the world better when you perform, always want to prove yourself better than a rival, and a sucker for a pretty face.", character_alignment: "Neutral-Good", character_notes: "hates dwarfs")
Character.create(character_template_id: template4.id, user_id: 4, campaign_id: 2, character_name: "Scoundrel 2", character_image: "", race_name: "Halfling", race_trait_name: "Halfling Nimbleness and Lucky", class_name: "Rogue", class_image: "", subclass_feature: "Sneak Attack: Deal an extra 1d6 damage once per turn if you have advantage on the attack roll.", race_proficiencies: "Dex +5, Int +4, keen to acrobatics.", character_background: "You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts within the criminal underworld. You have survived up to this point by flouting the rules and regulations of society.Your expertise is burglary. You are unmatched at getting into tight spaces and locked rooms, and getting back out again richer and none the worse. ", character_alignment: "Neutral", character_notes: "Strategist")
Character.create(character_template_id: template5.id, user_id: 5, campaign_id: 3, character_name: "Mage 1", character_image: "", race_name: "Dragon-Born", race_trait_name: "Breath-Weapon: Use your action to exhale cold energy in a 15-foot cone. Each creature in the area must make a DC Constitution saving throw. Dragonic Ancestry(Silver): Cold breath weapon and resistance to cold.", class_name: "Sorcerer", class_image: "", subclass_feature: "Spellcasting: Ability to cast sorcerer spells using Charisma, Spell Save DC: 13, Spell attack modifier: +5", race_proficiencies: "Con +4, Cha +6", character_background: "You grew up in the wilds, a fiercely proud member of a noble clan. The clan outweighs everything else in your life, even the stated law of the land. Wanderer: You have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided that the land offers berries, small game, water, and so forth. A member of the Emerald Enclave, you'd do anything to protect the clan, you have ideallic values, your clan is the most important thing in your life, you believe in survival of the fittest.", character_alignment: "Neutral-Good", character_notes: "Makes bad decisions")
Character.create(character_template_id: template6.id, user_id: 2, campaign_id: 1, character_name: "Mage 2", character_image: "", race_name: "Human", race_trait_name: "Martial Weapons, Passive Perception 12", class_name: "Druid", class_image: "", subclass_feature: "Spellcasting: Drawing on the divine essence of nature, you can cast spells to shape that essence to your will. Druidic: Speak druidic to leave hidden messages and decipher hidden messages", race_proficiencies: "Light Armor, Medium Armor, Shields.", character_background: "You come from among the peasantry, but the druids who taught you revealed your birth is in accord with a prophecy spoken long ago by mysterious fey. People of your home village regard you as a blessed one with the skills to stand against threats against common folk everywhere. Rustic Hospitality: You can find a place to hide, rest, or recuperate among commoners, unless you have shown yourself to be a danger to them. They will shield you from the law or anyone else searching for you, though they will not risk their lives for you. A member of the Emerald Enclave, you judge people by their actions and test them with strong words, tradition is very important, everything you do is to serve and protect the common folk, and you're convinced that everything that happens to you is part of your destiny.", character_alignment: "Neutral-Good", character_notes: "Is very very lucky")
Character.create(character_template_id: template7.id, user_id: 4, campaign_id: 3, character_name: "Healer 1", character_image: "", race_name: "Dwarf", race_trait_name: "Darkvision: You can see in the dark, Stonecutting: +4 bonus on Intelligence (History) checks related to stonecutting.", class_name: "Cleric", class_image: "", subclass_feature: "Life Dommain: Gain access to Disciple of Life: When you restore hitpoints to a creature, the creature gains additional hitpoints equal to +2 the spell's level. Spell Casting: Drawing on the divine essense of nature, you can cast spells to shape that essence to your will.", race_proficiencies: "Wis +5, Cha +3, advantage against being poisoned.", character_background: "Before you became devoted to the dwarven deities, you were a journeyman jeweler and gem cutter. Even outside your home, you are recognized by your badge and skill. You have the aid of a loose coalition of guilds, and one day you shall become a master your own right. Seeking such mastery is an act of worship to you. Guild Member: Fellow guild members can provide you with necessities, and the guild can use its political power to aid you. In some areas, a guildhall offers a place to meet other members of your profession and those who aid the guild. You must pay dues of 5 gp per month to the guild. If you miss payments, you must make up back dues to remain in the guild's good graces.", character_alignment: "Lawful-Good", character_notes: "Doesn't have a clue what's going on")
Character.create(character_template_id: template8.id, user_id: 3, campaign_id: 2, character_name: "Healer 2", character_image: "", race_name: "Human", race_trait_name: "Martial Weapons, Passive Perception 12", class_name: "Paladin", class_image: "", subclass_feature: "Divine Sense: Activite to gain awareness for the duration of your turn, revealing the location of any celestial, fiend, or undead within 60 feet of you that is not behind cover.", race_proficiencies: "Wis +3, Cha +4", character_background: "You were born the eighth child of a minor noble family. You are accustomed to privilege and the comforts that come with it, but recognizing that you will never inherit, you set out as a youth to find your own path.  Position of Privilege: Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are. The common folk make every effort to accommodate you and avoid your displeasure, and other people of high birth treat you as a member of the same social sphere. You can secure an audience with a local noble if you need to.", character_alignment: "Lawful-Good", character_notes: "Doesn't have a clue what's going on")

puts 'Seeding done, whew!'
# Character.new(user_id: nil, 
# campaign_id: nil, 
# character_name: nil, 
# character_image: nil, 
# race_name: nil, 
# race_trait_name: nil, 
# class_name: nil, 
# class_image: nil, 
# subclass_feature: nil, 
# race_proficiencies: nil, 
# character_background: nil, 
# character_alignment: nil, 
# character_notes: nil)
